[package]
name = "lightsUI"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.2", features = ["rt-multi-thread", "macros"] }
topcoat = { version = "0.10.0", features = ["tailwind"] }

[build-dependencies]
topcoat = { version = "0.10.0", default-features = false, features = ["tailwind"] }
